# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zheguang Samuel Zhao
email: zheguang.zhao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Box 1910, Computer Science Department
  Brown University
  Providence, RI 02912
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zheguang.github.io" # the base hostname & protocol for your site
twitter_username: zhegu
github_username:  zheguang

# Build Settings
# https://www.taniarascia.com/make-a-static-website-with-jekyll/
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
